---
- name: Connect to remote machine
  hosts: 127.0.0.1
  remote_user: ming

  tasks:
  - name: Compile redis source code
    shell: cd /home/ming/tar/redis-7.2 && make

  tasks:
  - name: Install redis
    shell: cd /home/ming/tar/redis-7.2 && sudo make install

  tasks:
  - name: Configure redis configuratio catelogs
    shell: sudo mkdir -p /etc/redis
    shell: sudo cp /home/ming/tar/redis-7.2/redis.conf /etc/redis/redis.conf
