---
- name: Connect to remote machine
  hosts: 127.0.0.1
  remote_user: ming

  tasks:
  - name: start_script
    file:
      path: "{{ installroot }}/startup.sh"
      state: touch
  - name: writting start script
    blockinfile:
      path: "{{ installroot }}/startup.sh"
      block: |
        redis-server "{{ installroot }}/7001/redis.conf"
        redis-server "{{ installroot }}/7002/redis.conf"
        redis-server "{{ installroot }}/7003/redis.conf"
        redis-server "{{ installroot }}/7004/redis.conf"
        redis-server "{{ installroot }}/7005/redis.conf"
        redis-server "{{ installroot }}/7006/redis.conf"
      state: present

  - name: stopScript
    file:
      path: "{{ installroot }}/stop.sh"
      state: touch
  - name: writting stop script
    blockinfile:
      path: "{{ installroot }}/stop.sh"
      block: |
        redis-cli -h 127.0.0.1 -p 7001 shutdown
        redis-cli -h 127.0.0.1 -p 7002 shutdown
        redis-cli -h 127.0.0.1 -p 7003 shutdown
        redis-cli -h 127.0.0.1 -p 7004 shutdown
        redis-cli -h 127.0.0.1 -p 7005 shutdown
        redis-cli -h 127.0.0.1 -p 7006 shutdown
        redis-cli -h 127.0.0.1 -p 7011 shutdown
        redis-cli -h 127.0.0.1 -p 7012 shutdown
        redis-cli -h 127.0.0.1 -p 7013 shutdown
        redis-cli -h 127.0.0.1 -p 26379 shutdown
        redis-cli -h 127.0.0.1 -p 26380 shutdown
        redis-cli -h 127.0.0.1 -p 26381 shutdown
      state: present
  - name: change privelige
    shell: chmod u+x "{{ installroot }}/stop.sh"

  - name: createCluster
    file:
      path: "{{ installroot }}/createCluster.sh"
      state: touch
  - name: writting createCluster script
    blockinfile:
      path: "{{ installroot }}/createCluster.sh"
      block: |
        redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006<<EOF
        yes
        EOF
      state: present
  - name: change privelige
    shell: chmod u+x "{{ installroot }}/createCluster.sh"


  - name: create slave script
    file:
      path: "{{ installroot }}/startSlave.sh"
      state: touch

  - name: writting slave script
    blockinfile:
      path: "{{ installroot }}/startSlave.sh"
      block: |
        redis-server "{{ installroot }}/7001/slave1/redis.conf"
        redis-server "{{ installroot }}/7001/slave2/redis.conf"
        redis-server "{{ installroot }}/7001/slave3/redis.conf"
      state: present

  - name: change privelige
    shell: chmod u+x "{{ installroot }}/startSlave.sh"

  - name: create sentinel script
    file:
      path: "{{ installroot }}/startSentinel.sh"
      state: touch

  - name: writting sentinel script
    blockinfile:
      path: "{{ installroot }}/startSentinel.sh"
      block: |
        redis-sentinel "{{ installroot }}/sentinel/sentinel_1.conf"
        redis-sentinel "{{ installroot }}/sentinel/sentinel_2.conf"
        redis-sentinel "{{ installroot }}/sentinel/sentinel_3.conf"
      state: present

  - name: change privelige
    shell: chmod u+x "{{ installroot }}/startSentinel.sh"
