---
- name: Connect to remote machine
  hosts: 127.0.0.1
  remote_user: ming

  tasks:
  - name: start_script
    file:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/startup.sh
      state: touch
  - name: writting start script
    blockinfile:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/startup.sh
      block: |
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7001/redis.conf
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7002/redis.conf
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7003/redis.conf
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7004/redis.conf
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7005/redis.conf
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7006/redis.conf
      state: present

  - name: stopScript
    file:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/stop.sh
      state: touch
  - name: writting stop script
    blockinfile:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/stop.sh
      block: |
        redis-cli -h 127.0.0.1 -p 7001 shutdown
        redis-cli -h 127.0.0.1 -p 7002 shutdown
        redis-cli -h 127.0.0.1 -p 7003 shutdown
        redis-cli -h 127.0.0.1 -p 7004 shutdown
        redis-cli -h 127.0.0.1 -p 7005 shutdown
        redis-cli -h 127.0.0.1 -p 7006 shutdown
        redis-cli -h 127.0.0.1 -p 7011 shutdown
        redis-cli -h 127.0.0.1 -p 7012 shutdown
        redis-cli -h 127.0.0.1 -p 7013 shutdown
        redis-cli -h 127.0.0.1 -p 26379 shutdown
        redis-cli -h 127.0.0.1 -p 26380 shutdown
        redis-cli -h 127.0.0.1 -p 26381 shutdown
      state: present
  - name: change privelige
    shell: chmod u+x /home/ming/redisPrac/ansible_redisCluster_sentinel/stop.sh

  - name: createCluster
    file:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/createCluster.sh
      state: touch
  - name: writting createCluster script
    blockinfile:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/createCluster.sh
      block: |
        redis-cli --cluster create 127.0.0.1:7001 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 127.0.0.1:7006<<EOF
        yes
        EOF
      state: present
  - name: change privelige
    shell: chmod u+x /home/ming/redisPrac/ansible_redisCluster_sentinel/createCluster.sh


  - name: create slave script
    file:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/startSlave.sh
      state: touch

  - name: writting slave script
    blockinfile:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/startSlave.sh
      block: |
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7001/slave1/redis.conf
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7001/slave2/redis.conf
        redis-server /home/ming/redisPrac/ansible_redisCluster_sentinel/7001/slave3/redis.conf
      state: present

  - name: change privelige
    shell: chmod u+x /home/ming/redisPrac/ansible_redisCluster_sentinel/startSlave.sh

  - name: create sentinel script
    file:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/startSentinel.sh
      state: touch

  - name: writting sentinel script
    blockinfile:
      path: /home/ming/redisPrac/ansible_redisCluster_sentinel/startSentinel.sh
      block: |
        redis-sentinel /home/ming/redisPrac/ansible_redisCluster_sentinel/sentinel/sentinel_1.conf
        redis-sentinel /home/ming/redisPrac/ansible_redisCluster_sentinel/sentinel/sentinel_2.conf
        redis-sentinel /home/ming/redisPrac/ansible_redisCluster_sentinel/sentinel/sentinel_3.conf
      state: present

  - name: change privelige
    shell: chmod u+x /home/ming/redisPrac/ansible_redisCluster_sentinel/startSentinel.sh
